Repository Newish0/seng468-day-trading, pull requests merged in 2025-03, with the labels that each got.

#45 fix(OM): added missing package.json changes
  package.json
  services/order-manager/package.json
Labels: urgent

#66 fix(OU): fixes problems found during integration
  docker-compose.yml
  packages/shared-models/RedisInstance.ts
  packages/shared-models/redisRepositoryHelper.ts
  services/gateway/nginx.conf
  services/order-update/src/handlers/orderUpdateHandler.ts
  services/order-update/src/services/orderUpdateService.ts
Labels: bug

#70 ME: `u64` for Stock Quantity
  .vscode/project.code-workspace
  services/matching-engine/README.md
  services/matching-engine/src/consumers.rs
  services/matching-engine/src/matching_pq.rs
  services/matching-engine/src/models.rs
Labels: bug

#65 added shading for order placement
  services/order-manager/src/services/rabbitMQService.ts
Labels: enhancement

#46 Matching Engine Sharding
  docker-compose.yml
  services/matching-engine/README.md
  services/matching-engine/src/consumers.rs
  services/matching-engine/src/main.rs
  services/matching-engine/src/rabbitmq.rs
Labels: enhancement
